markdown: rdiscount
permalink: /:year/:month/:title/
url: http://sbzhouhao.net
name: crazyEgg
author: Hao Zhou
email: hzhou@wpi.edu | zhouhao@mit.edu
version: 3.0
pygments: true
paginate: 25
paginate_path: "blog/page:num"